import { Inter, Source_Serif_4 } from 'next/font/google';
import Script from 'next/script';
import './globals.css';
import 'react-quill-new/dist/quill.snow.css';
import './quillStyles.css';
import { DatabaseProvider } from './context/DatabaseContext';
import { FocusModeProvider } from './context/FocusModeContext';
import NavBar from './components/NavBar';
import MobileDock from './components/MobileDock';
import AlertPopup from './alerts/AlertPopup';
import { AlertProvider } from './alerts/AlertContext';
import { THEME_STORAGE_KEY } from './lib/theme';

export const metadata = {
	title: 'Foli',
	description: 'Generated by Adam',
};

export const viewport = {
	width: 'device-width',
	initialScale: 1,
	viewportFit: 'cover',
};

const inter = Inter({ subsets: ['latin'] });

const sourceSerif4 = Source_Serif_4({
	subsets: ['latin'],
	variable: '--font-source-serif-4',
});

export default function RootLayout({ children }) {
	return (
		<html lang='en' data-theme='light' suppressHydrationWarning>
			<body className={`${inter.className} ${sourceSerif4.variable}`}>
				<Script id='foli-theme-init' strategy='beforeInteractive'>
					{`(function(){try{var t=localStorage.getItem('${THEME_STORAGE_KEY}');if(t==='light'||t==='dark'){document.documentElement.setAttribute('data-theme',t)}}catch(e){}})();`}
				</Script>
				<DatabaseProvider>
					<FocusModeProvider>
						<AlertProvider>
							{/* This is 'relative' so that the alert can be positioned 'absolute'. */}
							<div className='flex flex-col h-screen bg-base-200 relative'>
								<NavBar />
								<AlertPopup />
								<div className='grow min-h-0 overflow-y-auto pb-[calc(4rem+env(safe-area-inset-bottom))] md:pb-0'>
									{children}
								</div>
								<MobileDock />
							</div>
						</AlertProvider>
					</FocusModeProvider>
				</DatabaseProvider>
			</body>
		</html>
	);
}
